
MOVIE_ROOT_DIRECTORY = "Movies"

MOVIE_FILE_NAME = "movie"
MOVIE_FILE_FORMAT = "mp4"

MOVIE_VCODEC = "libx264"
MOVIE_ACODEC = "aac"

STORAGE_HOST = "localhost"
STORAGE_PORT = 8040

READ_SIZE = 1024*1024 * 32